import React from 'react';

const ZReport = ({ stats, dateFilter, customDates, user = 'Admin' }) => {
    const today = new Date().toLocaleDateString();
    const time = new Date().toLocaleTimeString();

    // Helper to format currency
    const formatCurrency = (val) => `Rs. ${(val || 0).toFixed(2)}`;

    // Resolve date range text
    let dateRangeText = dateFilter;
    if (dateFilter === 'Custom' && customDates.start && customDates.end) {
        dateRangeText = `${customDates.start} to ${customDates.end}`;
    } else if (dateFilter === 'Today') {
        dateRangeText = new Date().toLocaleDateString();
    }

    return (
        <div id="printable-z-report" className="hidden print:block bg-white p-8 max-w-3xl mx-auto text-black font-mono">
            {/* Header */}
            <div className="text-center mb-8 border-b-2 border-black pb-4">
                <h1 className="text-3xl font-bold uppercase tracking-wider mb-2">Pharmacy POS</h1>
                <h2 className="text-xl font-bold uppercase mb-4">Z-Report (End of Day)</h2>
                <div className="flex justify-between text-sm">
                    <span>Generated By: {user}</span>
                    <span>Printed: {today} {time}</span>
                </div>
                <div className="text-sm mt-1">
                    <span>Reporting Period: <strong>{dateRangeText}</strong></span>
                </div>
            </div>

            {/* Sales Summary */}
            <div className="mb-8">
                <h3 className="text-lg font-bold border-b border-black mb-3 pb-1">Sales Summary</h3>
                <div className="space-y-2 text-sm">
                    <div className="flex justify-between">
                        <span>Gross Sales</span>
                        <span>{formatCurrency(stats.grossSales)}</span>
                    </div>
                    <div className="flex justify-between text-red-600">
                        <span>Returns</span>
                        <span>- {formatCurrency(stats.returns)}</span>
                    </div>
                    <div className="flex justify-between text-gray-600">
                        <span>Discounts Given</span>
                        <span>- {formatCurrency(stats.discounts)}</span>
                    </div>
                    <div className="flex justify-between text-gray-600">
                        <span>Tax Collected</span>
                        <span>+ {formatCurrency(stats.tax)}</span>
                    </div>
                    <div className="flex justify-between font-bold text-lg mt-2 pt-2 border-t border-dashed border-gray-400">
                        <span>Net Sales</span>
                        <span>{formatCurrency(stats.netSales)}</span>
                    </div>
                </div>
            </div>

            {/* Transaction Counts */}
            <div className="mb-8">
                <h3 className="text-lg font-bold border-b border-black mb-3 pb-1">Transaction Activity</h3>
                <div className="space-y-2 text-sm">
                    <div className="flex justify-between">
                        <span>Total Transactions (Bills)</span>
                        <span>{stats.billsCount}</span>
                    </div>
                    <div className="flex justify-between">
                        <span>Items Sold</span>
                        <span>{stats.itemsSold}</span>
                    </div>
                    <div className="flex justify-between">
                        <span>Average Ticket Value</span>
                        <span>{stats.billsCount > 0 ? formatCurrency(stats.netSales / stats.billsCount) : formatCurrency(0)}</span>
                    </div>
                </div>
            </div>

            {/* Payment Breakdown */}
            <div className="mb-8">
                <h3 className="text-lg font-bold border-b border-black mb-3 pb-1">Payment Breakdown</h3>
                <div className="space-y-2 text-sm">
                    <div className="flex justify-between">
                        <span>Cash</span>
                        <span>{formatCurrency(stats.cashSales)}</span>
                    </div>
                    <div className="flex justify-between">
                        <span>Card</span>
                        <span>{formatCurrency(stats.cardSales)}</span>
                    </div>
                    <div className="flex justify-between">
                        <span>Credit / On-Account</span>
                        <span>{formatCurrency(stats.creditSales)}</span>
                    </div>
                    <div className="flex justify-between font-bold border-t border-gray-400 pt-1 mt-1">
                        <span>Total Collected</span>
                        {/* Note: Total Collected might differ from Net Sales due to Credits or rounding. 
                            Usually Total Collected = Cash + Card. Credit is 'Receivable'. 
                            For Z-Report, we usually sum actual payments. */}
                        <span>{formatCurrency((stats.cashSales || 0) + (stats.cardSales || 0))}</span>
                    </div>
                </div>
            </div>

            {/* Footer */}
            <div className="text-center text-xs mt-12 border-t border-black pt-4">
                <p>*** END OF REPORT ***</p>
                <p className="mt-1">Please retain this copy for audit purposes.</p>
            </div>
        </div>
    );
};

export default ZReport;
